### ISSUE TITLE
Недоработки в 22/Меняем цвет машины

### ISSUE THREAD

**Issue by Simplifier** [CSharpLords/homework-Lelouch19#11]
Все хорошо, но почему кнопки за пределами холста? Как по ним кликать?
![](https://api.monosnap.com/rpc/file/download?id=Io6Pt3awMyKRK1HUTYHEcEIfzPOXLG)

**Comment by Simplifier** [comment]
Не знаю, как у тебя это выглядит, но у меня кнопки все еще за экраном)
![](https://api.monosnap.com/rpc/file/download?id=9DimmfZqdYTlSun9SSzkJQvnKZvQw3)

**Comment by Lelouch19** [comment]
У меня вот так)
![1](https://user-images.githubusercontent.com/32432727/37242876-5b8ca45c-2481-11e8-926e-0d53d2397935.png)

**Comment by Simplifier** [comment]
Читай раздел [про якорные точки](https://github.com/UniumGames/Lessons/tree/master/11#rect-transform), чтоб понять, как сделать нормально для любого размера экрана
